name: bellevue-fd-zone-finder
static_sites:
  - name: fd-frontend
    github:
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: dist
    environment_slug: node-js
    routes:
      - path: /
